theme: jekyll-theme-slate
title: Rugged Software
description: “Rugged” describes software development organizations that have a culture of rapidly evolving their ability to create available, survivable, defensible, secure, and resilient software. 
show_downloads: false
google_analytics: UA-32996095-3
